server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-80

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#设置feign客户端超市时间
ribbon:
  #  指的是建立连接后，从服务器读取到可用资源所用的时间
  ReadTimeout: 5000 #这里的sleep就是模拟的这种readTime
  # 指的是建立连接所用的时间
  ConnectTimeout: 5000
logging:
  level:
    com.zmz.springcloud.service.PaymentFeignService: debug

